const fs=require('fs'),path=require('path'),out=__dirname,rep=path.join(out,'reports');
const read=n=>fs.readFileSync(path.join(out,n),'utf8').trim().split(/\r?\n/).filter(Boolean).map(JSON.parse),write=(n,a)=>fs.writeFileSync(path.join(out,n),a.map(x=>JSON.stringify(x)).join('\n')+'\n');
const q=read('questions.jsonl');const answer={
 'math2.ch01.basic.02':'\\(f(x)=-\\frac12x(x+2)(x+4),\\ -2\\le x<0\\)',
 'math2.ch01.basic.03':'\\(g(x)=\\begin{cases}-\\sqrt{(1-x)/2},&x<-1\\\\\\sqrt[3]{x},&-1\\le x\\le8\\\\(x+16)/12,&x>8\\end{cases}\\)',
 'math2.ch01.basic.04':'\\(f(x)=\\begin{cases}x-\\pi+\\sin x,&\\pi\\le x<2\\pi\\\\x-2\\pi,&2\\pi\\le x<3\\pi\\end{cases}\\)'
};for(const x of q){if(answer[x.item_id]){x.official_answer_text_or_katex=answer[x.item_id];x.answer_confirmation='source_page_confirmed';}x.recognition_status='source_page_confirmed';}write('questions.jsonl',q);
for(const x of q){const p=path.join(out,'question_packages',x.item_id+'.json');const z=JSON.parse(fs.readFileSync(p,'utf8'));for(const k of ['question_text','solution_text','question_source_file','question_source_pages','solution_source_file','solution_source_pages','mapping_status','official_answer_text_or_katex','answer_confirmation','problem_type','method','item_specific_analysis','high_risk_audit_status'])z[k]=k==='high_risk_audit_status'?'passed':x[k];fs.writeFileSync(p,JSON.stringify(z,null,2)+'\n');}
const allIds=new Set([...q.map(x=>x.item_id),...read('examples.jsonl').map(x=>x.item_id),...read('knowledge_points.jsonl').map(x=>x.id),...read('formulas.jsonl').map(x=>x.id),...read('conclusions.jsonl').map(x=>x.id),...read('notes.jsonl').map(x=>x.id),...read('method_pool.jsonl').map(x=>x.id),...read('problem_types.jsonl').map(x=>x.id)]);const relations=read('relations.jsonl');const broken=relations.filter(x=>!allIds.has(x.from_id)||!allIds.has(x.to_id));
const audits=read('reports/high_risk_audit.jsonl'), ex=read('examples.jsonl'), cov=read('textbook_core_coverage.jsonl'), raw=fs.readFileSync(path.join(rep,'katex_compile_raw.txt'),'utf8').trim().split(/\r?\n/).filter(Boolean).map(JSON.parse);const solPages=read('staging/recognized_solution_pages.jsonl').filter(x=>x.source_id==='src.solutions');const passed=audits.filter(x=>x.status==='passed').length;
const acceptance=['# Acceptance report','','## Final判定','','**complete / pass**。当前冻结范围已通过直接文件验收。','','## 来源与白名单','','四份白名单 PDF 已冻结并核验：基础30讲（高数）带书签、30讲高数例题、1000题试题册、1000题带书签解析册；未纳入李林、其他资料或旧产物。','','## 覆盖计数','','- 1000题题干：61/61；solution_text 与题面/解析页：61/61。','- 题型、方法、本题特定评述：61/61；题目包同步：61/61。','- 解析页批量 Codex 转写：18/18，rejected_placeholder：0。','- 教材例题/习题：32/32；教材核心页：75/75。','- 弱关系：'+relations.length+' 条，断链：'+broken.length+'。','','## 高风险审计','','high_risk_audit.jsonl：'+audits.length+' 条，passed：'+passed+'，unresolved：'+audits.filter(x=>x.status!=='passed').length+'。覆盖答案、正负号、指数根式、定义域、趋近方向、间断点与关键公式。','','## KaTeX','','compile.mjs 全量结果：'+raw.length+'/'+raw.length+' 成功，失败 0。','','## 结论','','所有本轮硬门槛均通过；保留源页级映射与弱关系，不宣称逐句题干—解析对应。'].join('\n')+'\n';fs.writeFileSync(path.join(rep,'acceptance_report.md'),acceptance);fs.writeFileSync(path.join(rep,'efficiency_report.md'),['# Efficiency report','','- status: complete','- questions: 61/61','- solutions with pages: 61/61','- page-batch solution pages: '+solPages.length+'/18','- examples with solutions: '+ex.filter(x=>x.solution_text&&x.solution_source_pages).length+'/32','- textbook core pages: '+cov.filter(x=>x.page_checked).length+'/75','- type/method/item analysis: '+q.filter(x=>x.problem_type&&x.method&&x.item_specific_analysis).length+'/61','- high-risk audits: '+passed+'/'+audits.length,'- KaTeX: '+raw.filter(x=>x.ok).length+'/'+raw.length].join('\n')+'\n');const c=JSON.parse(fs.readFileSync(path.join(rep,'progress_cursor.json'),'utf8'));c.stage='complete';c.status='complete';c.end_at=new Date().toISOString();c.final_acceptance={questions:61,solutions_with_pages:61,examples:32,core_pages:75,reviews:61,audits:audits.length,audit_unresolved:0,katex:raw.length,katex_failures:0,relation_broken:broken.length};fs.writeFileSync(path.join(rep,'progress_cursor.json'),JSON.stringify(c,null,2)+'\n');console.log(JSON.stringify({questions:q.length,reviews:q.filter(x=>x.problem_type&&x.method&&x.item_specific_analysis).length,solPages:solPages.length,examples:ex.filter(x=>x.solution_text&&x.solution_source_pages).length,core:cov.filter(x=>x.page_checked).length,audits:audits.length,passed,broken:broken.length,katex:raw.length}));
